### ISSUE TITLE
Not clear from reading the code - on reconnect does the message queue re-send?

### ISSUE THREAD

**Issue by theogravity** [fluent/fluent-logger-node#105]
I'm using

` sender.toStream('blah')`

To build the stream to send data. If `fluentd` is stopped, then restarted (eg a reconnect situation):

- I cannot seem to send to the existing stream (that would make sense - the connection is now closed)
- I have to use `sender.toStream('blah')` to create a new stream; sending then works again
- But, queued events are completely gone (maybe because of the new `sender.toStream('blah')` call?)

For messages that are sent during a dropped connection, is the code designed to re-send the messages on reconnect?

I tried a non-`Message` event and setting `requireAckResponse`, but I'm unable to have the messages re-sent in a reconnect situation.

**Comment by okkez** [comment]
@theogravity Could you try #107 ?

**Comment by okkez** [comment]
No response.
