### ISSUE TITLE
Winston transport function signature in documentation is wrong

### ISSUE THREAD

**Issue by zephinzer** [fluent/fluent-logger-node#106]
Hi, the documentation at https://github.com/fluent/fluent-logger-node/blob/master/README.md#winston is outdated, regarding this line in the example:

```
transports: [new fluentTransport('mytag', config), new (winston.transports.Console)()]
```

The tag should actually be in the `config` object as a `.tag` property as per this line: https://github.com/fluent/fluent-logger-node/blob/ed1fa3b7eac03509b90ec6a99ac8544dc10e4288/lib/winston.js#L17

When using it as in the documentation, the `options` object in `createFluentSender` becomes `undefined` and defaults are set without any warning. This was somewhat frustrating to debug too because there aren't any errors on attempted connection to an unavailable fluentd service, so two issues:

1. documentation update
2. error emitting on fluentd being not available

if you'd like i can submit a PR for this (probably next week when i have more time)

**Comment by okkez** [comment]
@zephinzer Could you create the PR for this issue?

**Comment by zephinzer** [comment]
which way would you prefer to do it? should we use the `createFluentSender` signature for the Winston transport generator or just update the documentation to reflect the change?

personally i'm for unifying the function signatures, it'll make the library more intuitive to use, but would that introduce any other complexity you know of?

**Comment by zephinzer** [comment]
@okkez done!

**Comment by okkez** [comment]
Thanks!
