### ISSUE TITLE
TypeScript support？

### ISSUE THREAD

**Issue by navono** [fluent/fluent-logger-node#109]

**Comment by okkez** [comment]
Could you create the PR to support TypeScript?

**Comment by navono** [comment]
I give it a try.

**Comment by okkez** [comment]
Thank you!!
I'm looking forward to see your PR.

**Comment by navono** [comment]
@okkez  I've already push a PR, please check it if you can.

**Comment by navono** [comment]
I wonder it's any possible to support browsers? because `winston@3.x.x` already dose.

**Comment by okkez** [comment]
I think this fluent-logger does not support browsers.
Because this uses raw TCP socket directly. (Modern browsers have not supported TCP Socket yet)
