### ISSUE TITLE
remove 0.6 build, introduce 0.10 build

### ISSUE THREAD

**Issue by yssk22** [fluent/fluent-logger-node#13]
Recent build error is from 0.6 engine (https://travis-ci.org/fluent/fluent-logger-node/jobs/16815111) during `npm install` and CI with 0.8 is fine (https://travis-ci.org/fluent/fluent-logger-node/jobs/16815112). It is a good chance to remove 0.6 and add 0.10 CI.

**Comment by okkez** [comment]
This issue is now outdated.
@repeatedly Could you close this issue?

**Comment by edsiper** [comment]
sorry for the delay, closing this issue.
