### ISSUE TITLE
TS: Winston dependency even if not using Winston transport

### ISSUE THREAD

**Issue by Kageetai** [fluent/fluent-logger-node#143]
I am using typescript for my project but don't use any winston transport whatsoever, but I am still required to install `winston` in my own projects dependencies, because otherwise build fails because of this line: https://github.com/fluent/fluent-logger-node/blob/master/lib/index.d.ts#L8

**Comment by okkez** [comment]
Hmm, winston-transport is an optional library in this fluent-logger-node.
I'm not familiar with TypeScript definitions (index.d.ts).

Can I remove type definitions related to winston-transport?

**Comment by Kageetai** [comment]
I am also not too familiar with the type definitions files, but is it auto-generated? If not just remove it probably.
Or add `winston-transport` to the dependencies`, so it will also be installed, when installing `fluent-logger-node`. But I think removing any notion to winston is better.

**Comment by VladaPetrovic** [comment]
Great for merging this fix into master. When can we expect new npm release ?
