### ISSUE TITLE
error TS2307: Cannot find module 'winston-transport'.

### ISSUE THREAD

**Issue by bivas6** [fluent/fluent-logger-node#156]
I'm try to use version: 3.3.1.
I have nothing with winston in my app, just want to create fluent-logger instance. I saw that this Issue has been reported  https://github.com/fluent/fluent-logger-node/issues/101 but I think it's might be back.
Thanks

**Comment by okkez** [comment]
Could you show me reproducible code and procedure?

**Comment by bivas6** [comment]
package.json: 
{
...    
     "dotenv": "^8.2.0",
    "fluent-logger": "^3.3.0",
    "fs": "0.0.2",
...
}

package-lock.json:

{
...
    "fluent-logger": {
      "version": "3.3.0",
      "resolved": "https://registry.npmjs.org/fluent-logger/-/fluent-logger-3.3.0.tgz",
      "integrity": "sha512-Ea5hbBcHcmPy3TdXKcVqwMFENxrAVP437jeSlXa3QsJ2AiMw+fj9QSVrQu0EFwVw7Jemg58mF5h5gt1gPSVWQw==",
      "requires": {
        "msgpack-lite": "*"
      }
    },
..  "msgpack-lite": {
      "version": "0.1.26",
      "resolved": "https://registry.npmjs.org/msgpack-lite/-/msgpack-lite-0.1.26.tgz",
      "integrity": "sha1-3TxQsm8FnyXn7e42REGDWOKprYk=",
      "requires": {
        "event-lite": "^0.1.1",
        "ieee754": "^1.1.8",
        "int64-buffer": "^0.1.9",
        "isarray": "^1.0.0"
      }
    },
...

logger.ts:


import * as fluentdLogger from 'fluent-logger';
class Logger {
  private _fluentLogger: fluentdLogger.FluentSender<{ log: string }>;
  constructor(logName: string) {
    this._logName = logName;
    logName = logName.replace(/ /g, '_');
    this._fluentLogger = fluentdLogger.createFluentSender(...);
}

Thanks!

**Comment by bivas6** [comment]
This problem has solved in @3.4.0 Thanks!
