### ISSUE TITLE
Cannot install fluent-logger-node on node 0.10

### ISSUE THREAD

**Issue by markokostovski** [fluent/fluent-logger-node#34]
I cannot deploy my application anymore. Even tho now it works on 4.0

msgpack@1.0.0: wanted: {"node":">=4.0.0"} (current: {"node":"0.10.38","npm":"1.4.28"})
...
npm ERR! Failed at the msgpack@1.0.0 install script.
npm ERR! This is most likely a problem with the msgpack package,

Can this be resolved?

**Comment by edsiper** [comment]
did you installed fluent-logger from npm or through this repo ?

**Comment by markokostovski** [comment]
npm

**Comment by markokostovski** [comment]
It's working with version 0.3.0 of fluent-logger
