### ISSUE TITLE
MsgPack pin versions

### ISSUE THREAD

**Issue by airtoxin** [fluent/fluent-logger-node#35]
currently release of msgpack1.0.0 has install errors on many platforms.
fluent-logger-node dependent msgpack but dependent package versions are currently not pined. so, npm try to install newest msgpack when installing this package and fail.
it should be pin stable version of dependent packages
```
     "dependencies": {
         "msgpack": "0.2.6"
     },
```

**Comment by xiaozhouzhou** [comment]
"msgpack": "0.2.6" works fine at node v0.10.24

**Comment by noraesae** [comment]
+1 for this. `0.2.7` also works find for me.

**Comment by edsiper** [comment]
@airtoxin @xiaozhouzhou @noraesae :

would you please confirm  each one of you that 0.2.7 works fine ?

**Comment by noraesae** [comment]
Yes it did work well. But now I've also tested with the master branch and it also worked fine. So I guess there would be no problem in the next release.

**Comment by edsiper** [comment]
After a few tests I have the following scenario:

| NodeJS version  | msgpack version  |  status                  |
|----------------------|-----------------------|----------------------|
|  v0.10.40              | 0.2.7                       |  OK                       |
|  v0.12.7                | 0.2.7                       | OK                        |
|  v4.0.0                  | 0.2.7                        | FAILED               |
|  v4.1.1                  | 0.2.7                        | FAILED               | 
|  v0.10.40              | 1.0.0                       |  FAILED               |
|  v0.12.7                | 1.0.0                       |  FAILED               |
|  v4.0.0                  | 1.0.0                        | OK                       |
|  v4.1.1                  | 1.0.0                        | OK                       | 

For short:

- NodeJS < 4.0 needs msgpack v0.2.7
- NodeJS >= 4.0 needs msgpack v1.0.0

Anyone of you knows a workaround to handle this in the package.json or any other ?

**Comment by edsiper** [comment]
I've released fluent-logger 0.3.0 on the npm site. This version is only compatible with Node < 4 and iojs < 3. 

Please test and send me some feedback.

**Comment by airtoxin** [comment]
it works fine

**Comment by markokostovski** [comment]
Working with v0.10.38, thx :+1:  Thx

**Comment by repeatedly** [comment]
Thanks for testing! Close this issue.
