### ISSUE TITLE
Layout is ignored

### ISSUE THREAD

**Issue by gregoryb** [fluent/fluent-logger-node#45]
When i configure an appender using a custom Layout, it's not used to format the message.
You should add a dependency to log4js in order to access to the layout function.

If you can't fix it quickly, i will try to fix it as a PR.

**Comment by okkez** [comment]
Thank you for reporting issue.
Patches are welcome!

**Comment by okkez** [comment]
@gregoryb Please show me your configuration for example. What do you want to do?
fluent-logger sends structured data to fluentd.
I think fluent-logger appender can ignore custom layout.

**Comment by okkez** [comment]
no response
