### ISSUE TITLE
how should we recorver if dequeued items are not sent.

### ISSUE THREAD

**Issue by orangemi** [fluent/fluent-logger-node#49]
Here is your comment at https://github.com/fluent/fluent-logger-node/blob/master/lib/sender.js#L153
I wonder whether a solution here? or any idea?

**Comment by okkez** [comment]
We can implement `require_ack_response option`.

See https://github.com/fluent/fluentd/wiki/Forward-Protocol-Specification-v0#response

**Comment by okkez** [comment]
Hmm, I have no idea.
I think we can detect `socket.write` is completed, cannot detect incomplete `socket.write`.

**Comment by slang800** [comment]
`requireAckResponse` should probably be the default. I would expect some kind of error to be thrown if a log message isn't forwarded properly, so I don't end up losing data and I can implement some kind of retry logic (if needed).

Not enabling `requireAckResponse` should just be a way to increase performance at the risk of losing data.

**Comment by okkez** [comment]
`requireAckResponse` should not be enabled by defaul. Because other fluent-logger-* and Fluentd built-in out_forward don't enable `require_ack_response` by default.
