### ISSUE TITLE
How to add timestamp to message data in winston + fluent transport

### ISSUE THREAD

**Issue by rqc** [fluent/fluent-logger-node#55]
Is there is a way to automatically include a timestamp in the `fluentTransport` as part of the message? I can see in the code that the packet to `fluentd` is sent with a timestamp created in the `FluentSender` but there is no way to include that or an application-generated timestamp to the data of the message. 

I guess the issue is that the `fluentTransport` does not support  _custom formatting_ of the message as it is done in other [winston transports](https://github.com/winstonjs/winston#custom-log-format). 

Thanks!

**Comment by okkez** [comment]
Some winston transports don't support custom formatter and other options.
For example, console transports and file transports support them, but http transports and memory transports don't.

Could you describe what do you want to do? I cannot imagine your situation.
I think timestamp which is added by fluent-logger is enough.

**Comment by rqc** [comment]
Thanks for your response @okkez. My scenario is the following (I am a newbie with `fluentd` so please let me know if I have other options to do this):
* Setup `fluent-logger` to output directly to `fluentd` including a timestamp as part of the `body` of the collected message itself.
* This message is stored in `elasticsearch` and it should have the `timestamp` included as part of the message. 

Instead, what is happening is that we are receiving the messages stored in `elasticsearch`, but we only have the timestamp (from what I can see) of the storage in `elasticsearch` and *not* the actual timestamp of the `fluent-logger`. Perhaps I can do some filtering / formatting in `fluentd` conf to extract the timestamp and inject it in the message's body?

**Comment by okkez** [comment]
Thank you for describing your case.

You can use filter_record_transformer in such case.
http://docs.fluentd.org/articles/filter_record_transformer

```aconf
<source>
  @type forward
  @label @TEST
</source>

<label @TEST>
  <filter>
    @type record_transformer
    <record>
       timestamp ${time}
    </record>
  </filter>

  <match **>
    @type elasticsearch
    # ... snip ...
  </match>
</label>
```

I don't confirm this configuration.
If you want inject timestamp into the message, see following example:

```aconf
<filter>
  @type record_transformer
  message ${time} ${record["message"]}
</filter>
```
