### ISSUE TITLE
MessagePack::MalformedFormatError

### ISSUE THREAD

**Issue by jurgenhaas** [fluent/fluent-logger-node#57]
When I'm emitting the following object, then I get a MessagePack::MalformedFormatError in FluentD:

```
{ timestamp: 2017-02-19T12:38:27.487Z,
  isUp: true,
  isResponsive: true,
  time: 490,
  monitorName: 'origin' }
```

The full error is this:

```
forward error error=#<MessagePack::MalformedFormatError: invalid byte> error_class=MessagePack::MalformedFormatError
```

When I convert all the values above to strings, then the error disappears but I'm not sure that's what is the correct way to resolve this. Any advise?

**Comment by okkez** [comment]
Could you show me your full configuration for Fluentd and your JavaScript code to emit log?
I could not reproduce your situation.

**Comment by jurgenhaas** [comment]
Sure, what I'm doing is to enhance an existing monitoring tool and the file I'm editing is this: https://gitlab.paragon-es.de/tools/uptime/blob/master/models/ping.js

In the header I've added this:

```
var logger = require('fluent-logger');
logger.configure('app.uptime', {
  host: 'localhost',
  port: 24224,
  timeout: 3.0,
  reconnectInterval: 60000
});
```

Then, the class builds a Ping object which will be written to a MongoDB in line 72.

In my first approach I have added the following code right before `ping.save()`:

```
logger.emit('test', ping);
```

That throws the error and as ping contains some other class objects, I thought I should simplify that and tried this:

```
var LoggerFields = ['timestamp', 'isUp', 'isResponsive', 'time', 'tags', 'monitorName', 'downtime', 'error'];
var log_output = {};
for (var i = 0, len = LoggerFields.length; i < len; i++) {
  var name = LoggerFields[i],
      value = ping.get(name);
  if (value != undefined) {
    log_output[name] = value;
  }
}
logger.emit('test', log_output);
```

That throws the same error. Then I casted `String(value)` which is then working OK.

Hope that helps you to reproduce this?

**Comment by okkez** [comment]
I got error `error_class=MessagePack::UnknownExtTypeError error="unexpected extension type` with following code:

```js
var logger = require('fluent-logger');
var mongoose = require('mongoose');
var Schema   = mongoose.Schema;
logger.configure('tag_prefix', {
   host: 'localhost',
   port: 24224,
   timeout: 3.0,
   reconnectInterval: 600000 // 10 minutes
});

var PingSchema = new Schema({
  timestamp    : { type: Date, default: Date.now },
  isUp         : Boolean,  // false if ping returned a non-OK status code or timed out
  isResponsive : Boolean,  // true if the ping time is less than the check max time
  time         : Number,
  check        : { type: Schema.ObjectId, ref: 'Check' },
  tags         : [String],
  monitorName  : String,
  // for pings in error, more details need to be persisted
  downtime     : Number,   // time since last ping if the ping is down
  error        : String,
  details      : Schema.Types.Mixed
});

var Ping = mongoose.model('Ping', PingSchema);

var ping = new Ping();
// console.log(JSON.stringify(ping));
//console.log(typeof ping.timestamp);
logger.emit('ping', ping);
```

Maybe `ping.timestamp` is not plain JavaScript object so Fluentd cannot decode from msgpack.
You can send plain JavaScript object with fields what you want (your code is almost good).

Or `logger.emit('ping', JSON.parse(JSON.stringify(ping)));`

**Comment by jurgenhaas** [comment]
Thanks, that should do.
