### ISSUE TITLE
Switch to using node.js core library `Agent` for socket pooling

### ISSUE THREAD

**Issue by NawarA** [fluent/fluent-logger-node#58]
Reading through the source code, it looks like a new socket is made on every invocation. Both memory and CPU time performance can be improved by switching to node's core Agent class, which by default includes socket pooling, which will reuse existing sockets, instead making a new socket every time.

Can you confirm socket pooling isnt currently being used?

**Comment by okkez** [comment]
Could you take the benchmark?
Is node's core Agent class [http.Agent](https://nodejs.org/api/http.html)?
This module uses [net.Socket](https://nodejs.org/api/net.html#net_class_net_socket) because Fluentd does not speak HTTP(S).

**Comment by okkez** [comment]
No response.

**Comment by NawarA** [comment]
Sorry, didnt see your question until I got the most recent GitHub notification. And yes, that's right.

When you say
`This module uses net.Socket because Fluentd does not speak HTTP(S).`

Do you mean it speaks UDP, not TCP?

**Comment by okkez** [comment]
This module uses TCP to talk with Fluentd.
All fluent-logger follow [Forward protocol specification](https://github.com/fluent/fluentd/wiki/Forward-Protocol-Specification-v0).

**Comment by NawarA** [comment]
Exactly. Instead of creating a new socket every time, you can use's Node's built in HTTP (TCP) module, which will manage socket reuse / pooling for you. This will make this module more efficient than creating a new socket every log -- which is not a good idea of high throughput servers.

@JoshFerge does this make sense?

**Comment by okkez** [comment]
HTTP is constructed on TCP and also Fluentd's forward protocol is original protocol constructed on TCP.
Fluentd's forward protocol is not HTTP.
So we cannot use Node's build-in HTTP module for Fluentd's forward protocol.

**Comment by okkez** [comment]
No response.
