### ISSUE TITLE
fluentd update to v0.14 EventTime

### ISSUE THREAD

**Issue by linxuanwei** [fluent/fluent-logger-node#59]
can you support EvenTime in fluent-logger-node

**Comment by okkez** [comment]
Sure.

**Comment by linxuanwei** [comment]
@okkez 

Great！ You are so handsome！ 
[https://github.com/fluent/fluentd/wiki/Forward-Protocol-Specification-v1#entry](url)
[http://www.rubydoc.info/gems/fluentd/Fluent/EventTime](url)

[https://github.com/fangli/fluent-plugin-influxdb/issues/71](url)

[https://github.com/fangli/fluent-plugin-influxdb/pull/72](url)

**Comment by linxuanwei** [comment]
![qq20170302-180957 2x](https://cloud.githubusercontent.com/assets/10094722/23503172/75704d88-ff75-11e6-98ee-61e442c1808b.jpg)
how to realise this using msgpack?
@okkez

**Comment by okkez** [comment]
I will investigate this issue and support EventTime in this month.
Please wait! :guitar:

**Comment by linxuanwei** [comment]
@okkez  Great！ See it.

Look forward to your submission.
