### ISSUE TITLE
How to know if the socket is connected?

### ISSUE THREAD

**Issue by linxuanwei** [fluent/fluent-logger-node#60]
I would like to do some processing when the socket connection was
connected, and  do some processing when the connection was disconnected.

@okkez

**Comment by okkez** [comment]
I will investigate this in next week or later.

**Comment by okkez** [comment]
Could you describe your scenario?

**Comment by linxuanwei** [comment]
@okkez  eg.

I would send something to slack when fluent-logger-node was disconnected with fluentd

and

I would do something when fluent-logger-node reconnected with fluentd.

**Comment by okkez** [comment]
> I would send something to slack when fluent-logger-node was disconnected with fluentd

You can try following code:

```js
var logger = require('fluent-logger').createFluentSender('tag_prefix', {
   host: 'localhost',
   port: 24224,
   timeout: 3.0,
   reconnectInterval: 600000 // 10 minutes
});
logger.on('error', function(error) {
   console.log(error); // Notify error to slack
});
```

I will implement connect event as following:

```js
logger.on('connect', function() {
  console.log('connected!'); // But we cannot recognize re-connection after error.
});
```

**Comment by linxuanwei** [comment]
Can only be so
