### ISSUE TITLE
program not gracefully terminating after logger.emit()

### ISSUE THREAD

**Issue by hassanf1** [fluent/fluent-logger-node#79]
Hi, I am using fluent-logger for the first time.
after logger.emit() the control doesnt return to my nodeJS program. 

Is it something that I am missing?

My code ******:
```
var logger = require('fluent-logger')
// The 2nd argument can be omitted. Here is a default value for options. 
logger.configure('mongo', {
   host: 'localhost',
   port: 24224,
   timeout: 3.0,
   reconnectInterval: 180000 // 3 minutes 
});
 
// send an event record with 'tag.label' 
logger.emit('info', 
    {
        type: 'info',
        message: {name: 'testprogram', description: 'hello world 111', timestamp: (new Date()).toString()},
        notif: false,
        caller: 'mylibrary/test.js'
    });
```

My fluent.conf file*******:

```
<source>
  @type forward
  port 24224
</source>
<match mongo.**>
  @type mongo
  host 192.168.8.152
  port 27017
  database TransactionData
  collection logs
  include_time_key true
  time_key time

  # flush
  flush_interval 10s
</match>

```
*********
I can see my logs going to mongoDB using logger.emit(). But my test program doesn't terminate when I use logger.emit() statement.

Thanks
Farrukh

**Comment by okkez** [comment]
`logger.emit()` creates new socket and the socket keeps running until call `logger.end()`.
You can gracefully stop your program calling `logger.end()` after `logger.emit()`.

**Comment by hassanf1** [comment]
I see. 
When I applied end() immediately after emit() my logs were not written. Probably the socket get closed before log was written. However putting a delay (like setTimeout) before end() worked...

`logger.emit('info', 
    {
        type: 'info',
        message: {name: 'testprogram', description: 'hello world 223', timestamp: (new Date()).toString()},
        notif: false,
        caller: 'mylibrary/test.js'
    });

setTimeout(function() {
  logger.end();  
}, 1000);`

In my actual scenario I need to keep running a service and write multiple logs on regular intervals or events.  In such case do I need to call end() at some point or not?

Thanks,
Farrukh

**Comment by okkez** [comment]
>  In such case do I need to call end() at some point or not?

Maybe, you can call `end()` while your application's shutdown sequence.
If you don't call `end()` on shutdown, your application will not terminate gracefully.

**Comment by hassanf1** [comment]
Sure. Thanks for your feedback.
