### ISSUE TITLE
AWS Lambda timing out due to open socket.

### ISSUE THREAD

**Issue by memosstilvi** [fluent/fluent-logger-node#89]
We are currently using your library in some of our AWS Lambda functions.

The way we use it is as a Stream in our bunyan logger. 
Even though everything seems to be working fine, and the logs reach our backend log aggregator servers, the Lambdas keep timing ou 100% of the time.

setting 
```javascript
context.callbackWaitsForEmptyEventLoop = false
```
seems to help to get rid of the timeouts, however the logs stop being sent to the backend.

We haven't nailed down the issue 100% but it seems very likely that the timeouts are happening because of your library leaving connections/sockets open.

Can someone please advise?

**Comment by okkez** [comment]
You can stop logger like following:

```js
'use strict';
const Console = require('console').Console;
var sender = require('fluent-logger').createFluentSender('tag.prefix', {
   host: 'localhost',
   port: 24224,
   timeout: 3.0,
   reconnectInterval: 600000 // 10 minutes
});
var logger = new Console(sender.toStream('stdout'), sender.toStream('stderr'));
logger.log('this log record is sent to fluent daemon');
setTimeout(()=> sender.end(), 5000);
```

**Comment by memosstilvi** [comment]
@okkez Thank you for your answer.
Are we sure that all the messages will be sent if we close the sender like that?

**Comment by okkez** [comment]
> Are we sure that all the messages will be sent if we close the sender like that?

Yes. We can wait ack response from Fluentd with `requireAckResponse: true` option.

```js
'use strict';
const Console = require('console').Console;
var sender = require('fluent-logger').createFluentSender('tag.prefix', {
  host: 'localhost',
  port: 24224,
  timeout: 3.0,
  reconnectInterval: 600000, // 10 minutes
  requireAckResponse: true
});
var stdout = sender.toStream('stdout');
var stderr = sender.toStream('stderr');
var logger = new Console(stdout, stderr);
logger.log('this log record is sent to fluent daemon');
sender.end('end', {"message": "end of message!!"});
```

**Comment by nikhilkakade2108** [comment]
I am facing the same issue. calling setTimeout() works for me. But execution time plays major role in costing of lambda functions, in my case we cannot afford to freeze lambda function just for logging purpose.
Is there any way available to end fluentdsender without using setTimeout().

Also, how it works properly in case of winston support transport?

**Comment by okkez** [comment]
@nikhilkakade2108 See [winston section](https://github.com/fluent/fluent-logger-node#winston) in README.md.

**Comment by okkez** [comment]
#91 is relevant to this issue.
