### ISSUE TITLE
Define log levels

### ISSUE THREAD

**Issue by MerkAndreas** [fluent/fluent-logger-node#97]
Is it possible to define log levels like in winston, to log only the specified levels?
And if yes, how could it be implemented?

Thanx and regards,
Andreas

**Comment by okkez** [comment]
Use log4js-fluent-appender or winston transport to filter logs by log level.
fluent-logger-node cannot filter logs by log level.

**Comment by MerkAndreas** [comment]
Too Bad...
Thanx for your fast response!

**Comment by damianprzygodzki** [comment]
It's bother as hell. You support winston transport but not in exactly right way and tell us to do it on our own.
