### ISSUE TITLE
in non-message mode, queue size seems to grow indefinitely

### ISSUE THREAD

**Issue by theogravity** [fluent/fluent-logger-node#98]
I'm looking at the memory profile using this module, and I noticed that `this._sendQueueSize` never gets reset to 0 after send operations.

https://github.com/fluent/fluent-logger-node/blob/a2fcc64e0fef21a2d2fc286fa82964aa4bccf644/lib/sender.js#L42

Is this intentional? Shouldn't it decrement or reset to 0 during certain conditions?

**Comment by okkez** [comment]
Thank you for reporting.
It is an unexpected behavior. We must reset to 0 after flush `sendQueue`.

**Comment by okkez** [comment]
Released v2.8.0
